import Foundation

public struct Branch : Codable {
    let acceptDeposit : String?
    let accessEnDetails : String?
    let accessEnIdent : String?
    let accessFrDetails : String?
    let accessFrIdent : String?
    let address : String?
    let alternatePhone : String?
    let alternativePhone : String?
    let bankN : String?
    let bankID : String?
    let bClass : String?
    let bInto : String?
    let boc : String?
    let branchN : String?
    let branchNRetail : String?
    let branchStatus : String?
    let branchStatusDate : String?
    let branchType : String?
    let brmng : String?
    let bStat : String?
    let casUnit : String?
    let cFaxNo : String?
    let costCenter : String?
    let coun : String?
    let creditFax : String?
    let currencies : String?
    let customBankDescription : String?
    let dataCenter : String?
    let depository : String?
    let designationN : String?
    let distance : String?
    let division : String?
    let driveUp : String?
    let driveUpHours : BusinessHours?
    let dvpnm : String?
    let emergencyPhone : String?
    let envelopeFree : String?
    let faxNo : String?
    let gm : String?
    let greenMachine : String?
    let hours : BusinessHours?
    let id : String?
    let interA : String?
    let interB : String?
    let isShutDown : String?
    let languages : String?
    let lat : String?
    let lng : String?
    let mainIntersection : String?
    let miscA : String?
    let miscB : String?
    let miscC : String?
    let name : String?
    let nearestSchool : String?
    let nearestShoppingMall : String?
    let nightDepository : String?
    let nightMessaging : String?
    let openDate : String?
    let pennyArcade : String?
    let pgi : String?
    let phoneNo : String?
    let phoneType : String?
    let regionalManager : String?
    let safetyDepositBoxes : String?
    let sdb : String?
    let shutDownReason : String?
    let srvicingBSC : String?
    let submergeClosInto : String?
    let tdAccessArea : String?
    let tdArea : String?
    let thirdPartyVideoID : String?
    let timestamp : String?
    let timezoneID : String?
    let transit : String?
    let type : String?
    let upd : String?
    let updater : String?
    let visaCenter : String?
    let voiceEnabled : String?
    let wheelchair : String?
}

public struct BusinessHours : Codable {
    let monday : String?
    let tuesday : String?
    let wednesday : String?
    let thursday : String?
    let friday : String?
    let saturday : String?
    let sunday : String?
}
